version: '3.8'

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'

  frontend:
    image: nginx:1.17.1-alpine
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - '80:80'